{% set name = "allennlp" %}
{% set version = "0.7.0" %}
{% set file_ext = "tar.gz" %}
{% set hash_type = "sha256" %}
{% set hash_value = "58d82bf09a4d2dcf80e925fd42007e44040c5afd7085db31660a492bd2ed747c" %}

package:
  name: '{{ name|lower }}'
  version: '{{ version }}'

source:
  fn: '{{ name }}-{{ version }}.{{ file_ext }}'
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ file_ext }}
  '{{ hash_type }}': '{{ hash_value }}'

build:
  skip: True  # [win or py<36]
  number: 0
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - pip
    - python
  run:
    - python
    - pytorch >=0.4.1,<0.5.0
    - jsonnet ==0.10.0
    - typing
    - overrides
    - nltk
    - spacy >=2.0,<2.1
    - numpy
    - tensorboardx ==1.2
    - cffi ==1.11.5
    - awscli >=1.11.91
    - boto3
    - moto ==1.3.4
    - flask ==0.12.4
    - flask-cors ==3.0.3
    - gevent ==1.3.6
    - requests >=2.18
    - tqdm >=4.19
    - editdistance
    - h5py
    - scikit-learn
    - scipy
    - pytz ==2017.3
    - unidecode
    - matplotlib ==2.2.3
    - numpydoc ==0.8.0
    - conllu ==0.11
    - wget
    - perl
    - openjdk
    - pytest
    - flaky
    - parsimonious ==0.8.0
    - responses >=0.7
    - msgpack-python >=0.5.6,<0.6.0
    - ftfy
    - sqlparse ==0.2.4

test:
  imports:
    - allennlp
    - allennlp.commands
    - allennlp.common
    - allennlp.common.testing
    - allennlp.data
    - allennlp.data.dataset_readers
    - allennlp.data.dataset_readers.coreference_resolution
    - allennlp.data.dataset_readers.dataset_utils
    - allennlp.data.dataset_readers.reading_comprehension
    - allennlp.data.dataset_readers.semantic_parsing
    - allennlp.data.dataset_readers.semantic_parsing.wikitables
    - allennlp.data.fields
    - allennlp.data.iterators
    - allennlp.data.token_indexers
    - allennlp.data.tokenizers
    - allennlp.models
    - allennlp.models.coreference_resolution
    - allennlp.models.encoder_decoders
    - allennlp.models.reading_comprehension
    - allennlp.models.semantic_parsing
    - allennlp.models.semantic_parsing.atis
    - allennlp.models.semantic_parsing.nlvr
    - allennlp.models.semantic_parsing.quarel
    - allennlp.models.semantic_parsing.wikitables
    - allennlp.modules
    - allennlp.modules.attention
    - allennlp.modules.matrix_attention
    - allennlp.modules.seq2seq_encoders
    - allennlp.modules.seq2vec_encoders
    - allennlp.modules.similarity_functions
    - allennlp.modules.span_extractors
    - allennlp.modules.text_field_embedders
    - allennlp.modules.token_embedders
    - allennlp.nn
    - allennlp.nn.regularizers
    - allennlp.predictors
    - allennlp.semparse
    - allennlp.semparse.contexts
    - allennlp.semparse.executors
    - allennlp.semparse.type_declarations
    - allennlp.semparse.worlds
    - allennlp.service
    - allennlp.service.predictors
    - allennlp.state_machines
    - allennlp.state_machines.states
    - allennlp.state_machines.trainers
    - allennlp.state_machines.transition_functions
    - allennlp.tools
    - allennlp.training
    - allennlp.training.metrics
  requires:
    - jupyter
    - ipykernel <5.0.0
  commands:
    # Travis' OSX tests require more open files.
    - 'if [[ $TRAVIS == true ]]; then ulimit -n 2048 ; fi'  # [osx]
    - 'python -m nltk.downloader punkt'
    - 'curl -L https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-2.0.0/en_core_web_sm-2.0.0.tar.gz -o ~/en_core_web_sm-2.0.0.tar.gz'
    - 'tar -xf ~/en_core_web_sm-2.0.0.tar.gz -C ~'
    - 'python -m spacy link ~/en_core_web_sm-2.0.0/en_core_web_sm en_core_web_sm'
    - 'allennlp test-install'
    - 'rm ~/en_core_web_sm-2.0.0.tar.gz'
    - 'rm -rf ~/en_core_web_sm-2.0.0'

about:
  home: https://github.com/allenai/allennlp
  license: Apache 2.0
  license_family: Apache
  license_file: LICENSE
  summary: An open-source NLP research library, built on PyTorch.
  description: An open-source NLP research library, built on PyTorch.
  doc_url: 'https://allenai.github.io/allennlp-docs/'
  dev_url: 'https://github.com/allenai/allennlp'

extra:
  recipe-maintainers:
    - nelson-liu
